### ISSUE TITLE
Load pre-built crl and add new revoked certificate? Is there a limit?

### ISSUE THREAD

**Issue by ftbarata** [wbond/crlbuilder#2]
Hello, is it possible or how to load a certificate revoked list file and add new revoked certificate, incrementing the crl serial?

If it's not possible, so I guess I'll need to store all the revoked certificates in a database and the current crl serial position, then,  on every new revoked certificate, I'll need to loop over all the serials, and recreate the crl file. Is that correct?

**Comment by ftbarata** [comment]
I found this:

https://stackoverflow.com/questions/4115523/is-there-a-simple-way-to-parse-crl-in-python

But I couldn't find the way for retrieve the CRL number to make me able to increase it on every crl generation.

**Comment by wbond** [comment]
asn1crypto allows full access to the entirety of the CRL data structure, so you should definitely be able pull out the current serial number and the list of all certificates with reasons.

To do something like this, you could read over all of https://github.com/wbond/asn1crypto/blob/master/asn1crypto/crl.py and become familiar with the structure of CRL info.

You should be able to load an existing CRL and then just update the serial and add a new `asn1crypto.crl.RevokedCertificate` to the end of `asn1crypto.crl.CertificateList['tbs_cert_list']['revoked_certificates']`. Unfortunately I don't have time to create an example, but it shouldn't be too many lines of code.
