### ISSUE TITLE
ValueError: issuer certificate must have a key identifier extension to be used for signing CRLs

### ISSUE THREAD

**Issue by ftbarata** [wbond/crlbuilder#5]
I'm getting this error when using  CertificateListBuilder. But my certificate has AuthorityKeyIdentifier. I didn't understand. Below a copy of the certificate I'm trying to use:

```
-----BEGIN CERTIFICATE-----
MIIHuzCCBaOgAwIBAgIIb9K5/ZthR+QwDQYJKoZIhvcNAQELBQAwdTELMAkGA1UE
BhMCQlIxEzARBgNVBAoMCklDUC1CcmFzaWwxNjA0BgNVBAsMLVNlY3JldGFyaWEg
ZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAwwQQUMg
U0VSQVNBIFJGQiB2NTAeFw0xODA4MDIxNjAwMDBaFw0yMTA4MDExNjAwMDBaMIH3
MQswCQYDVQQGEwJCUjELMAkGA1UECAwCUkoxFzAVBgNVBAcMDlJJTyBERSBKQU5F
SVJPMRMwEQYDVQQKDApJQ1AtQnJhc2lsMTYwNAYDVQQLDC1TZWNyZXRhcmlhIGRh
IFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsMDVJGQiBl
LUNOUEogQTMxEjAQBgNVBAsMCUFSIFNFUkFTQTFJMEcGA1UEAwxARkVERVJBQ0FP
IE5BQ0lPTkFMIERFIEFQT0lPIEFPUyBFU1RVREFOVEVTIEJSQVNJTDoxMjY0MTE2
ODAwMDE2NTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAI+R4lc4avb0
C1PYm8jMc9mO2d2+ifknt9yzKN6EKPyf6nr9P/KwJHlXJl7Pv8VqbVBYuR+tnNpg
FrLl1DBJIuUGqCmfIh+/RGnSsULFJBT4b31G8bD+1cXATxvhVJHalh2euCaHmLsA
JrSRWLT+LqzW/UIZq+nTDLL33dxL9SeHlTow/+X4JFfoEZvlJgNTN+D9fUQhxw4f
BbL5D6kZODt5VZHAq/Y8XgHzOWsCGwIpzU94revPj0uflv/Y514uADv+JSLwlNH1
gct64H3Yo7SmRXks7wGRX2xmkxmD6EOHtEQVbMnYpqmVJrAH2M9VCFQZsYzo7z9X
uarjrrarUpkCAwEAAaOCAsowggLGMAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAU7PFB
UVeo5jrpXrOgIvkIirU6h48wgZkGCCsGAQUFBwEBBIGMMIGJMEgGCCsGAQUFBzAC
hjxodHRwOi8vd3d3LmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvY2FkZWlhcy9z
ZXJhc2FyZmJ2NS5wN2IwPQYIKwYBBQUHMAGGMWh0dHA6Ly9vY3NwLmNlcnRpZmlj
YWRvZGlnaXRhbC5jb20uYnIvc2VyYXNhcmZidjUwgbkGA1UdEQSBsTCBroEaRklO
QU5DRUlST0BTT1VGRU5FQi5PUkcuQlKgIgYFYEwBAwKgGRMXUkFGQUVMIEJFTE1J
Uk8gREEgU0lMVkGgGQYFYEwBAwOgEBMOMTI2NDExNjgwMDAxNjWgOAYFYEwBAwSg
LxMtMDQwMzE5ODMwOTEzNzU2MDc1MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw
oBcGBWBMAQMHoA4TDDAwMDAwMDAwMDAwMDBxBgNVHSAEajBoMGYGBmBMAQIDCjBc
MFoGCCsGAQUFBwIBFk5odHRwOi8vcHVibGljYWNhby5jZXJ0aWZpY2Fkb2RpZ2l0
YWwuY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9kZWNsYXJhY2FvLXJmYi5wZGYwHQYD
VR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIGdBgNVHR8EgZUwgZIwSqBIoEaG
RGh0dHA6Ly93d3cuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9yZXBvc2l0b3Jp
by9sY3Ivc2VyYXNhcmZidjUuY3JsMESgQqBAhj5odHRwOi8vbGNyLmNlcnRpZmlj
YWRvcy5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL3NlcmFzYXJmYnY1LmNybDAOBgNV
HQ8BAf8EBAMCBeAwDQYJKoZIhvcNAQELBQADggIBAK6P5BF6j4exagRC7Gomgv58
ir2JqOVaqXvuBYnTbcpAJigzAi1PdwaZf9GRy6dMU0qveYZdl38A6wBXTGrdAXRu
OKLdMKR/8Ji+B3nd3Hu1KBVlhug52asia0YJXdVjD+JMamABTKTbyB9wkeaXinZ1
836ArrUx0lVuXapVQx29KE4s4VMi0LPWmImnDt2AslQ685pp/ppnUTFWUvYrAiea
MjJSlwZeMzeYKicK2Ninnz/5CrazMvjdfEZzPIIDshJVs8KoPcQ0IQvFr45Grxav
vAPmZyW1uvaFGOz1pCd4D7WL6baIIjBuVNYPpVHX2pFcEGTT+NkSavGPqDkhM6CQ
MlqJyQiPHeAmmlxROzzfJv4fmRmcaNo2rrpVPtpn6rQwImk82edkLQF+CgXY8HXx
3h3IXwgh9KyTI54Lu4bghNCPXSCZWVmD9j8fpQSP8Wb3zDATwmAwrTsokXhGNzz/
B/JSudOO1lAJ9rRt6L7wXtuAmoGoe1TxeFXbDV36sHT7yE+nx+aEIQ+pfmGiZ5Ki
BKaC93KUlj1uiVjNpWKDA1Lsm5xtaHWVQYj3zMcvFQZet49WZSNpNsAzP+D5vTPW
FZyPZhlM5z/PIzpqy8QUwf6MvBh5fBULlTOeKCnolkujB6Y5soeayhamUcPgstJI
NM/HmpnRqTGV0R0JSw/y
-----END CERTIFICATE-----
```
However, I tried to use the letsencrypt certificate for testing and it works. Below a copy of letsencrypt certificate:

```
-----BEGIN CERTIFICATE-----
MIIGxDCCBaygAwIBAgISA/4JgcRKQNViQMvtPNEzNDXIMA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTAxMDgxMDI0NDdaFw0x
OTA0MDgxMDI0NDdaMB0xGzAZBgNVBAMTEmNlcnQuc3ltZW50LmNvbS5icjCCAiIw
DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMVx9EYvZdeslXHtgw+sMVFIv5ME
G5Ihqu7YSD75o2Z0u0uZS11EgyuczP7jioO/5e7Z/ADwo2DepdG9jam/eUktDDF0
GqYERyShyHbjABrU051IUY2D6tXWB5rboxsSXfryIJFzwqbuQA9QXegGJHc2lun+
WS/iWnQGCYIQEti4JqulAIaFMGKZLldXi35Gy0A3vox3ycXg9+4KWmjeaJ+hDnsQ
X11tzeKyvHvQtGnh5uG2nHnFbzTS7yCvoCkwC8X2w1CJRzVEaHIXh5O0U1IcRQr2
gaZ0330oQ9Q3xE3wIGVKuMEPXjy6wUigqCw1g4/9lUVJ6DSCX1rcy5GUd5DiC/E9
dm2Bpb/jGz+3rv/wSQY/FbbwRcrppp1XERvrWdDuikG6FpzZxwW3bmJblG8je4TG
i+/1YwsuVOQ8UA6lxTMF2BJF1SXdtlMjKsT1CeUw/oUxFYvF92lIgHjPQLY3WxKV
wkP38e+Ad667ZaNHPxZVSqypLZzy4g37FU9fzMfUH7juuz7b6kssL+XtzryXHlur
dWn9JVtIdiYNc1LkblOHbdEmMgv1TW2s1IeZzmnpDi/33Dy4eUjY+bWE6KOOkQbC
kEoINp2KvDyyVLf/Q9YsORcFdNicP/wCWup90Ydtyq7MX3o3Mpf9iEu/q9mT+mU3
5iIxYNRf1R2XPQ0vAgMBAAGjggLPMIICyzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0l
BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYE
FH+fCePgP2rLxmFw4wg5LQGUerUtMB8GA1UdIwQYMBaAFKhKamMEfd265tE5t6ZF
Ze/zqOyhMG8GCCsGAQUFBwEBBGMwYTAuBggrBgEFBQcwAYYiaHR0cDovL29jc3Au
aW50LXgzLmxldHNlbmNyeXB0Lm9yZzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQu
aW50LXgzLmxldHNlbmNyeXB0Lm9yZy8wgYMGA1UdEQR8MHqCFGNlcnQuc291ZmVu
ZWIub3JnLmJyghJjZXJ0LnN5bWVudC5jb20uYnKCGHZhbGlkYS5zb3BhZ29tZWlh
LmNvbS5icoIWd3d3LmNlcnQuc3ltZW50LmNvbS5icoIcd3d3LnZhbGlkYS5zb3Bh
Z29tZWlhLmNvbS5icjBMBgNVHSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEB
ATAoMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQUG
CisGAQQB1nkCBAIEgfYEgfMA8QB2AHR+2oMxrTMQkSGcziVPQnDCv/1eQiAIxjc1
eeYQe8xWAAABaC01M5YAAAQDAEcwRQIgNXGBK5mVmJz8aStxonR1n1u6NAwKvKjw
F6EQxsMh6hsCIQC5jXWwtTfyV9PvkjWz0fj5vPfLLwCFzA1Uzm4IEdmMHgB3ACk8
UZZUyDlluqpQ/FgH1Ldvv1h6KXLcpMMM9OVFR/R4AAABaC01Mh8AAAQDAEgwRgIh
AJ+x3ThAYCCyKfvwfm9EkhjqP5Zx1LrCjYnasb0ZDszlAiEAzTlfxD+zNI2LCELp
vhSUgDaTwS2uIBhRfGa2yBzE1QYwDQYJKoZIhvcNAQELBQADggEBAJbWtSPrPvbx
VJeKe/vroziM8Ww/YGoY4/e+qhaxbZIKzob+nmY7jBOVpJobM9PX8gmpZIsQEqMa
SU+1EBY++5bHCHSRfQi+PzcoVmp5wB5C+ewPmySvo5y6ohhN2XqlOZDKkNHGzGQY
clumH0Rax03f91D0y/vW+qxDcYLcJRgvr60yXiXH+xAEvebBqavBOuksbopW3iPr
kGnDZ8uhnU1HaeUOBVZ59nnVJL/eWbYbV9adORyspmQ/NdpDhLQDh2GdBQB+WnkZ
oANQMdOWmVVwSfSHJFOn8CE7I1psmyY/sT7fuocFgJ2Sgs5s2O4SonOyw6r+ArbR
nN8kD4I40WQ=
-----END CERTIFICATE-----
```

**Comment by wbond** [comment]
It sounds like you need to read https://tools.ietf.org/html/rfc5280#section-4.2.1.1 and https://tools.ietf.org/html/rfc5280#section-4.2.1.2.

**Comment by wbond** [comment]
To expand: an authority key identifier points to the issuer of the certificate. The subject key identifier is the identifier for a CA (issuing) certificate.

I do think considering how much work you are doing with certs that you read through at least RFC 5280 once if you haven't already. There are lots of subtle details about the PKI infrastructure, so getting familiar with everything that goes into it is going to be very helpful.

**Comment by ftbarata** [comment]
Thank you @wbond . I am reading now all you send.

**Comment by ftbarata** [comment]
@wbond thanks a lot again. Well, I've already read those rfc parts but I've just read them again. Please correct me if I'm wrong. 

The key identifier field in the Authority Key Identifier extension is a hash of the issuer's public key, so the applications can identify the public key corresponding to the private key which was used to sign the current certificate.

The Subject Key Identifier is another extension, used for identifying the certificates that contain a particular public key. According to the RFC 5280, all certificates that have cA:TRUE must have this extension. It's not much clear for me this concept, so, if you don't mind, I'd like to ask two questions:


1) I have an USB eToken that contains some AC certificates and one certificate in which cA is False. This particular certificate is what I have to use to sign that attribute certificate you helped me before. Everything is working fine but I've just saw this error while building the CRL. If you use any certificate decoder to take a look at the first pem cert I've posted, you'll see it just contains the authority key identifier extension. Since it's in octect string, I don't know if it has that KeyIdentifier field. The second pem(letsencrypt) has the subjectKeyIdentifier and authorityKeyIdentifier extensions. They're in octet string too and I don't know the fields within them. But the conclusion is that the let's encrypt certificate should have the KeyIdentifier field of authorityKeyIdentifier extension, and it's what your library tries do read. Is that correct? So the certificate I'm using to sign attribute certificate cannot be used to sign the CRL, right? If so, I'll try to ask the issuer if he can reissue a new certificate for me, including the keyIdentifier field.  I wonder why both letsencrypt and my certificate have cA:False and letsencrypt works for signing the CRL.


2) From RFC 5280: "The subject key identifier extension provides a means of identifying
   certificates that contain a particular public key." I'm trying to think in a situation for this. Would it be the case of Let's Encrypt? This CA issues milions of certificates, and all of these certificates have the same subject key identifier, and it's value must be the same as the key identifier field of Authority Key Identifier, which is that public key hash. Well, what's the need of two extensions that have the same value? Anyway, it's not so clear for me.

**Comment by ftbarata** [comment]
@wbond , sorry for my low knowledgement in PKI. I've finally understood the difference between aki and ski.
I've found this:
http://www.pkiglobe.org/aki_ski.html
which has a well good explanation about these two extensions.
So, to summarize my doubts:

1) Your CertificateListBuilder library looks for the SKI and the certificate I'm using just have the AKI right?
2) Please disconsider my previous question 2). The pkigloble article answers it.

**Comment by wbond** [comment]
Yes, crlbuilder requires a subject key identifier. This is an identifier given to your certificate, so that issued certificates or crls know what key to use when verifying them. The authority key identifier indicates the subject key identifier of what signed it. So by having an authority key identifier on your cert, that just indicates what created your cert. If you need to sign a CRL, you need to have a subject key identifier on your cert so that when processing the CRL the code knows to use your cert to verify it.

**Comment by ftbarata** [comment]
@wbond thank you so much. At the time you was writing your answer, I was reading this:
https://tools.ietf.org/html/rfc5280#page-60, which has:

"The identification can be based on either the key
   identifier (the subject key identifier in the CRL signer's
   certificate) or the issuer name and serial number."

And

"Conforming CRL issuers MUST use the key identifier method, and MUST
   include this extension in all CRLs issued."

So, thanks again

**Comment by ftbarata** [comment]
@wbond , just one more question please.
From rfc 5280, the key identifier is calculated excluding the tag, length, and number of unused bits of the public key. But I don't make any idea of how to do it. So,  when building the 'extn_value': AuthorityKeyIdentifier,  if I pass in the OctetString of the public key to 'key_identifier", will your library compute the SHA1 automatically or I need to pass in the Octet String previously calculated?
